app/bp_admin/__init__.py
from flask import Blueprint

bp = Blueprint('bp_admin', __name__, url_prefix='/admin', static_folder='static', template_folder='templates')

from app.bp_admin import routes, models

app/bp_admin/routes.py
from app.models import Usuario
from app.bp_admin import bp
from flask import render_template, request, redirect, url_for, flash
from flask_login import current_user, login_user, logout_user
from werkzeug.urls import url_parse

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('bp_admin.index.html')


@bp.route('/register', methods=['GET', 'POST'])
def register():
    return render_template('bp_admin.register.html')

@bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    return render_template('bp_admin.forgot_password.html')

@bp.route('/page_404', methods=['GET', 'POST'])
def page_404():
    return render_template('bp_admin.page_404.html')

@bp.route('/blank', methods=['GET', 'POST'])
def blank():
    return render_template('bp_admin.blank.html')

@bp.route('/charts', methods=['GET', 'POST'])
def charts():
    return render_template('bp_admin.charts.html')

@bp.route('/tables', methods=['GET', 'POST'])
def tables():
    return render_template('bp_admin.tables.html')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    username = request.form.get('username')
    if current_user.is_authenticated and current_user.perfil == 'admin':
        return redirect(url_for('bp_admin.index'))
    elif current_user.is_authenticated and current_user.perfil != 'admin':
        return redirect(url_for('bp_main.index'))    
    if request.method == 'POST':              
        email = request.form.get('email')
        senha = request.form.get('password')
        remember = request.form.get('remember_me')
        usuario = Usuario.query.filter_by(email=email).first()
        if usuario is None or not usuario.check_password(senha):
            flash('Nome de usuário ou senha inválido!')
            return render_template('bp_admin.login.html', resultado=request)
        login_user(usuario, remember=remember)
        next_page = request.form.get('next')
        print('>>>>>nextpage>>>>>', next_page)
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('bp_main.index')
        return redirect(next_page)
    return render_template('bp_admin.login.html', resultado=request)

@bp.route('/base', methods=['GET', 'POST'])
def base():
    return render_template('bp_admin.base.html')

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('bp_main.index'))

app/bp_admin/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  {% block head %}{% endblock %}  

</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="{{ url_for('bp_admin.index') }}">Eletiva Web</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('bp_admin.index') }}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Login Screens:</h6>
          <a class="dropdown-item" href="{{ url_for('bp_admin.login') }}">Login</a>
          <a class="dropdown-item" href="{{ url_for('bp_admin.register') }}">Register</a>
          <a class="dropdown-item" href="{{ url_for('bp_admin.forgot_password') }}">Forgot Password</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Other Pages:</h6>
          <a class="dropdown-item" href="{{ url_for('bp_admin.page_404') }}">404 Page</a>
          <a class="dropdown-item" href="{{ url_for('bp_admin.blank') }}">Blank Page</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('bp_admin.charts') }}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('bp_admin.tables') }}">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>
    </ul>

    {% block alerta %}
      {% with messages = get_flashed_messages() %}
        {% for message in messages %}
        <div class="my-1">
          {% if 'vindo' in message or 'sucesso' in message %}
            {% include "alerta_success.html" %}
            {% block voltar %}{% endblock %}
          {% else %}
            {% include "alerta_danger.html" %}            
          {% endif %}
        </div>
        {% endfor %}      
      {% endwith %}
    {% endblock %}
    
    <div id="content-wrapper">

      <div class="container-fluid">

        {% block content %}{% endblock %}
        
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Your Website 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ url_for('bp_admin.logout') }}">Logout</a>
        </div>
      </div>
    </div>
  </div>
  

  <!-- Bootstrap core JavaScript-->
  {% block bootstrap_core_javascript %}{% endblock %}
  

</body>

</html>

app/bp_admin/templates/blank.html
{% extends 'bp_admin.base.html' %}


{% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Eletiva Web 2019 - Blank Page</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('bp_admin.static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{{ url_for('bp_admin.static', filename='vendor/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('bp_admin.static', filename='css/sb-admin.css') }}" rel="stylesheet">
{% endblock %}


{% block content %}        
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{{ url_for('index') }}">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Blank Page</li>
  </ol>

  <!-- Page Content -->
  <h1>Blank Page</h1>
  <hr>
  <p>This is a great starting point for new custom pages.</p>
{% endblock %}


  <!-- Bootstrap core JavaScript-->
{% block bootstrap_core_javascript %}  
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('bp_admin.static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ url_for('bp_admin.static', filename='js/sb-admin.min.js') }}"></script>
{% endblock %}

app/bp_admin/templates/charts.html
{% extends 'bp_admin.base.html' %}


{% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Eletiva Web 2019 - Charts</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('bp_admin.static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{{ url_for('bp_admin.static', filename='vendor/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('bp_admin.static', filename='css/sb-admin.css') }}" rel="stylesheet">
{% endblock %}


{% block content %}        
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Charts</li>
  </ol>

  <!-- Area Chart Example-->
  <div class="card mb-3">
    <div class="card-header">
      <i class="fas fa-chart-area"></i>
      Area Chart Example</div>
    <div class="card-body">
      <canvas id="myAreaChart" width="100%" height="30"></canvas>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
  </div>

  <div class="row">
    <div class="col-lg-8">
      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-chart-bar"></i>
          Bar Chart Example</div>
        <div class="card-body">
          <canvas id="myBarChart" width="100%" height="50"></canvas>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-chart-pie"></i>
          Pie Chart Example</div>
        <div class="card-body">
          <canvas id="myPieChart" width="100%" height="100"></canvas>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
    </div>
  </div>

  <p class="small text-center text-muted my-5">
    <em>More chart examples coming soon...</em>
  </p>
{% endblock %}


  <!-- Logout Modal-->


  <!-- Bootstrap core JavaScript-->
{% block bootstrap_core_javascript %}
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('bp_admin.static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/chart.js/Chart.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ url_for('bp_admin.static', filename='js/sb-admin.min.js') }}"></script>

  <!-- Demo scripts for this page-->
  <script src="{{ url_for('bp_admin.static', filename='js/demo/chart-area-demo.js') }}"></script>
  <script src="{{ url_for('bp_admin.static', filename='js/demo/chart-bar-demo.js') }}"></script>
  <script src="{{ url_for('bp_admin.static', filename='js/demo/chart-pie-demo.js') }}"></script>
{% endblock %}

app/bp_admin/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Eletiva Web 2019 - Forgot Password</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('bp_admin.static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('bp_admin.static', filename='css/sb-admin.css') }}" rel="stylesheet">

</head>

<body class="bg-dark">

  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Reset Password</div>
      <div class="card-body">
        <div class="text-center mb-4">
          <h4>Forgot your password?</h4>
          <p>Enter your email address and we will send you instructions on how to reset your password.</p>
        </div>
        <form>
          <div class="form-group">
            <div class="form-label-group">
              <input type="email" id="inputEmail" class="form-control" placeholder="Enter email address" required="required" autofocus="autofocus">
              <label for="inputEmail">Enter email address</label>
            </div>
          </div>
          <a class="btn btn-primary btn-block" href="{{ url_for('bp_admin.login') }}">Reset Password</a>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="{{ url_for('bp_admin.register') }}">Register an Account</a>
          <a class="d-block small" href="{{ url_for('bp_admin.login') }}">Login Page</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('bp_admin.static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

</body>

</html>

app/bp_admin/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Eletiva Web 2019 - Login</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('bp_admin.static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('bp_admin.static', filename='css/sb-admin.css') }}" rel="stylesheet">

</head>

<body class="bg-dark">

  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login</div>
      <div class="card-body">
        <form method="post" action="{{ url_for('bp_admin.login') }}">
          
            {% block alerta %}
              {% with messages = get_flashed_messages() %}
                {% for message in messages %}
                  <div class="mb-2">
                    {% if 'vindo' in message or 'sucesso' in message %}
                      {% include "_alerta_success.html" %}
                      {% block voltar %}{% endblock %}
                    {% else %}
                      {% include "_alerta_danger.html" %}            
                    {% endif %}
                  </div>
                {% endfor %}      
              {% endwith %}
            {% endblock %}  
          
          <div class="form-group">
            <div class="form-label-group">
              <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="required" autofocus="autofocus" 
                value="{{ resultado.form.get('email', '') }}" name="email">
              <label for="inputEmail">Email address</label>
            </div>
          </div>
          <div class="form-group">
            <div class="form-label-group">
              <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="required"
                name="password">
              <label for="inputPassword">Password</label>
            </div>
          </div>
          <div class="form-group">
            <div class="checkbox">
              <label>
                <input type="checkbox" value="remember-me" name="remember_me" 
                {% if resultado.form.get('remember_me', '') %} checked {% endif %}>
                Remember Password
              </label>
            </div>
          </div>
          <input type="hidden" name="next" value="{{ resultado.args.get('next', '') }}">
          <button type="submit" class="btn btn-primary btn-block" name="LOGIN">Login</button>
          
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="{{ url_for('bp_admin.register') }}">Register an Account</a>
          <a class="d-block small" href="{{ url_for('bp_admin.forgot_password') }}">Forgot Password?</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('bp_admin.static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

</body>

</html>

app/bp_admin/templates/page_404.html
{% extends 'bp_admin.base.html' %}



{% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Eletiva Web 2019 - 404 Error</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('bp_admin.static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{{ url_for('bp_admin.static', filename='vendor/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('bp_admin.static', filename='css/sb-admin.css') }}" rel="stylesheet">
{% endblock %}


{% block content %}        
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{{ url_for('bp_admin.index') }}">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">404 Error</li>
  </ol>

  <!-- Page Content -->
  <h1 class="display-1">404</h1>
  <p class="lead">Page not found. You can
    <a href="javascript:history.back()">go back</a>
    to the previous page, or
    <a href="{{ url_for('bp_admin.index') }}">return home</a>.</p>
{% endblock %}


<!-- Logout Modal-->


{% block bootstrap_core_javascript %}
  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('bp_admin.static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
<script src="{{ url_for('bp_admin.static', filename='js/sb-admin.min.js') }}"></script>
{% endblock %}

app/bp_admin/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Eletiva Web 2019 - Register</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('bp_admin.static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('bp_admin.static', filename='css/sb-admin.css') }}" rel="stylesheet">

</head>

<body class="bg-dark">

  <div class="container">
    <div class="card card-register mx-auto mt-5">
      <div class="card-header">Register an Account</div>
      <div class="card-body">
        <form>
          <div class="form-group">
            <div class="form-row">
              <div class="col-md-12">
                <div class="form-label-group">
                  <input type="text" id="firstName" class="form-control" placeholder="Username" required="required" autofocus="autofocus">
                  <label for="firstName">Username</label>
                </div>
              </div>              
            </div>
          </div>
          <div class="form-group">
            <div class="form-label-group">
              <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="required">
              <label for="inputEmail">Email address</label>
            </div>
          </div>
          <div class="form-group">
            <div class="form-row">
              <div class="col-md-6">
                <div class="form-label-group">
                  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="required">
                  <label for="inputPassword">Password</label>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-label-group">
                  <input type="password" id="confirmPassword" class="form-control" placeholder="Confirm password" required="required">
                  <label for="confirmPassword">Confirm password</label>
                </div>
              </div>
            </div>
          </div>
          <a class="btn btn-primary btn-block" href="{{ url_for('bp_admin.login') }}">Register</a>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="{{ url_for('bp_admin.login') }}">Login Page</a>
          <a class="d-block small" href="{{ url_for('bp_admin.forgot_password') }}">Forgot Password?</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('bp_admin.static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('bp_admin.static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

</body>

</html>